# Generated by Django 2.2.4 on 2019-10-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191013_0036'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Order'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='orders',
            field=models.ManyToManyField(blank=True, to='products.Order'),
        ),
    ]
