# Generated by Django 2.2.4 on 2019-10-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='orderItem',
            field=models.ManyToManyField(blank=True, related_name='affiliate_item_list', to='products.OrderItem'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_seller', to='users.UserExtended'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_user', to='users.UserExtended'),
        ),
        migrations.AddField(
            model_name='productaffiliate',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
        migrations.AddField(
            model_name='productaffiliate',
            name='orderItem',
            field=models.ManyToManyField(blank=True, related_name='affiliate_product', to='products.OrderItem'),
        ),
        migrations.AddField(
            model_name='productaffiliate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_affiliate_user', to='users.UserExtended'),
        ),
    ]
