# Generated by Django 2.2.4 on 2019-10-12 18:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pencil work', 'Pencil work'), ('Pastel colours', 'Pastel colours'), ('Water colours', 'Water colours'), ('Acrylic colours', 'Acrylic colours'), ('Fabric colours', 'Fabric colours'), ('Oil colours', 'Oil colours'), ('Mix media', 'Mix Media')], max_length=20, unique=True)),
                ('gst', models.FloatField()),
                ('serviceCharge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('faq_of', models.CharField(choices=[('seller', 'seller'), ('user', 'user')], default='seller', max_length=10)),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.ImageField(upload_to='MainBanner/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pencil work', 'Pencil work'), ('Pastel colours', 'Pastel colours'), ('Water colours', 'Water colours'), ('Acrylic colours', 'Acrylic colours'), ('Fabric colours', 'Fabric colours'), ('Oil colours', 'Oil colours'), ('Mix media', 'Mix Media')], max_length=20, unique=True)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.NewsletterEmails')),
            ],
        ),
    ]
