# Generated by Django 2.2.4 on 2019-10-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilitesicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilitesIcon',
        ),
    ]
