# Generated by Django 2.2.4 on 2019-10-12 18:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('fname', models.CharField(default='', max_length=40)),
                ('lname', models.CharField(default='', max_length=40)),
                ('gstNumber', models.CharField(default='', max_length=30)),
                ('experience', models.IntegerField(default=0)),
                ('specialty', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10)),
                ('profile_img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='seller/profile_images/')),
                ('cover_img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='seller/cover_images/')),
                ('basic_profile_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellerExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('totalEarning', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(max_length=450)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('Pencil_work', models.BooleanField(default=False)),
                ('Pastel_colours', models.BooleanField(default=False)),
                ('Water_colours', models.BooleanField(default=False)),
                ('Acrylic_colours', models.BooleanField(default=False)),
                ('Fabric_colours', models.BooleanField(default=False)),
                ('Oil_colours', models.BooleanField(default=False)),
                ('Mix_media', models.BooleanField(default=False)),
                ('description_profile_completed', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('rating', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_comments', to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address_profile_completed', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seller/portfolio_images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
    ]
