# Generated by Django 2.2.4 on 2019-10-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191013_0036'),
        ('users', '0002_auto_20191013_0036'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='sellerItems', to='products.Item'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_from_user', to='users.UserExtended'),
        ),
        migrations.AddField(
            model_name='sellercomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserExtended'),
        ),
    ]
