# Generated by Django 2.2.4 on 2019-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='contactNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
