# Generated by Django 2.2.4 on 2019-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='bankName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payments',
            name='accountNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payments',
            name='cif',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fullName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
