# Generated by Django 2.2.4 on 2019-10-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Choose a name for your project')),
                ('description', models.TextField(verbose_name='Describe a little bit about your project')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Pencil work', 'Pencil work'), ('Pastel colours', 'Pastel colours'), ('Water colours', 'Water colours'), ('Acrylic colours', 'Acrylic colours'), ('Fabric colours', 'Fabric colours'), ('Oil colours', 'Oil colours'), ('Mix media', 'Mix media')], max_length=25, verbose_name='Tell us the category of your project')),
                ('is_active', models.BooleanField(default=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('assignedOn', models.DateTimeField(blank=True, null=True)),
                ('completedOn', models.DateTimeField(blank=True, null=True)),
                ('budget', models.CharField(choices=[('Less then 3000', 'Less then 3000'), ('4000 - 7000', '4000 - 7000'), ('8000 - 13000', '8000 - 13000'), ('14000 - 18000', '14000 - 18000'), ('19000 - 24000', '19000 - 24000'), ('More than 24000', 'More than 24000')], max_length=35, verbose_name='Tell us the budget for your project')),
                ('sampleImage', models.ImageField(blank=True, null=True, upload_to='project_images')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bided_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_in', models.IntegerField()),
                ('amount', models.FloatField()),
                ('proposal', models.TextField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_on', to='bids.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_by', to='seller.Seller')),
            ],
        ),
    ]
