# Generated by Django 2.2.4 on 2019-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Alert', 'Alert'), ('OrderSuccess', 'OrderSuccess'), ('OrderIncomplete', 'OrderIncomplete'), ('ProjectAssigned', 'ProjectAssigned'), ('ProjectArrived', 'ProjectArrived'), ('ProjectCompleted', 'ProjectCompleted'), ('BidAdded', 'BidAdded'), ('AccountSecurity', 'AccountSecurity'), ('PaymentDue', 'PaymentDue'), ('PaymentSuccess', 'PaymentSuccess'), ('registerdAsSeller', 'registerdAsSeller'), ('AddressUpdated', 'AddressUpdated'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archieve', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
