# Generated by Django 2.2.4 on 2019-10-12 18:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Pencil work', 'Pencil work'), ('Pastel colours', 'Pastel colours'), ('Water colours', 'Water colours'), ('Acrylic colours', 'Acrylic colours'), ('Fabric colours', 'Fabric colours'), ('Oil colours', 'Oil colours'), ('Mix media', 'Mix Media')], max_length=20)),
                ('subCategory', models.CharField(blank=True, choices=[('Abstract', 'Abstract'), ('Conceptual', 'Conceptual'), ('Digital Age', 'Digital Age'), ('Everyday Life', 'Everyday Life'), ('Fantasy', 'Fantasy'), ('Fashion', 'Fashion'), ('Figurative', 'Figurative'), ('Fine Art', 'Fine Art'), ('Historical and Political', 'Historical and Political'), ('Landscape', 'Landscape'), ('Marine', 'Marine'), ('Nature', 'Nature'), ('Nude', 'Nude'), ('Pop Culture', 'Pop Culture'), ('Portrait', 'Portrait'), ('Provocative', 'Provocative'), ('Religion', 'Religion'), ('Self Portrait', 'Self Portrait'), ('Still Life', 'Still Life'), ('Street Art', 'Street Art'), ('Urban', 'Urban'), ('Vanitas', 'Vanitas'), ('Other', 'Other')], default='Other', max_length=50, null=True)),
                ('originalPrice', models.FloatField()),
                ('originalDiscount_price', models.FloatField(blank=True, default=None, null=True)),
                ('serviceCharge', models.FloatField(blank=True, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('shortDescription', models.CharField(max_length=150)),
                ('makingTime', models.IntegerField(default=0)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('createdOn', models.DateTimeField(blank=True, null=True)),
                ('affiliatePaid', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('ordered_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('billing_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Coupon')),
                ('item', models.ManyToManyField(related_name='item_list', to='products.OrderItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='item_images')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='products.Item')),
            ],
        ),
    ]
