# Generated by Django 2.2.4 on 2019-10-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191013_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='originalDiscount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serviceCharge',
        ),
        migrations.AddField(
            model_name='item',
            name='addFrame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='finallySubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='frameCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='settlement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PackageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageLength', models.FloatField(blank=True, null=True)),
                ('packageWidth', models.FloatField(blank=True, null=True)),
                ('packageHeight', models.FloatField(blank=True, null=True)),
                ('packageWeight', models.FloatField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
    ]
