# Generated by Django 2.2.4 on 2019-10-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191013_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='colour',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='makingTime',
            new_name='dispatch_time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='fullDescription',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='hsn',
            new_name='hsnCode',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='published',
            new_name='listing_status',
        ),
    ]
