# Generated by Django 2.2.4 on 2019-10-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191013_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='width',
            new_name='length',
        ),
    ]
