# Generated by Django 2.2.4 on 2019-10-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_searchkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listing_status',
            field=models.BooleanField(default=True),
        ),
    ]
